name: main
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.23", "1.22", "1.21"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run mod-check
        run: make mod-check

      - name: Run tests
        run: make test

      - name: Send coverage
        if: ${{ matrix.version == '1.23' }}
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=profile.cov -service=github
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --timeout=3m
